*#NUMPY DAY2*

day16 numpy day3

In [20]:
import numpy as np
# *ARRAY CREATION : CONVERSION FROM OTHER PYTHON STRUCTUres
listarray= np.array([[1,2,3],[4,5,6],[87,8,9]])
listarray
listarray.dtype
listarray.size

9

In [21]:
zeros=np.zeros((2,5))
zeros
zeros.dtype
zeros.shape

(2, 5)

In [22]:
rng=np.arange(15)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
lspace=np.linspace(1,5,12)
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [24]:
emp=np.empty((4,6))
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.29061074e-306, 7.56587585e-307, 1.37961302e-306],
       [1.05699242e-307, 8.01097889e-307, 1.78020169e-306,
        7.56601165e-307, 1.02359984e-306, 1.33510679e-306],
       [2.22522597e-306, 8.01097889e-307, 1.42417629e-306,
        8.45593934e-307, 6.89805151e-307, 8.45606157e-307],
       [1.78019082e-306, 1.29061414e-306, 8.45559303e-307,
        1.06811422e-306, 1.05694828e-307, 1.42410974e-306]])

In [25]:
emp_like=np.empty_like(lspace)
emp_like


array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [26]:
ide=np.identity(45)
ide
ide.shape

(45, 45)

In [27]:
arr=np.arange(99)
arr
arr.reshape(3,33)
arr
arr=arr.reshape(3,33)
arr
arr=arr.ravel()
arr
arr.shape

(99,)

*#NUMPY DAY3*


In [28]:
x=[[1,3,5],[4,5,6],[7,1,0]]
ar = np.array(x)
ar
ar.sum(axis=0)
ar.sum(axis=1)
ar.T
for item in ar.flat:
    print(item)
ar.ndim
ar.size
ar.nbytes


1
3
5
4
5
6
7
1
0


72

In [47]:
ar
ar.argmin()
ar.argmax()
ar.argmax(axis=0)
ar.argmax(axis=1)
ar.argsort(axis=1)
ar.argsort(axis=0)


array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [48]:
one=np.array([1,3,4,634,2])
one.argmax()
one.argmin()
one.argsort()

array([0, 4, 1, 2, 3])

In [59]:
ar2=np.array([[1,2,1],[4,0,6],[8,1,0]])
ar2
ar+ar2
ar
ar*ar2
np.sqrt(ar)
ar.sum()
ar.max()

np.int64(7)