*#NUMPY DAY2*

In [1]:
import numpy as np
# *ARRAY CREATION : CONVERSION FROM OTHER PYTHON STRUCTUres
listarray= np.array([[1,2,3],[4,5,6],[87,8,9]])
listarray
listarray.dtype
listarray.size

9

In [ ]:
zeros=np.zeros((2,5))
zeros
zeros.dtype
zeros.shape

(2, 5)

In [7]:
rng=np.arange(15)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
lspace=np.linspace(1,5,12)
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [9]:
emp=np.empty((4,6))
emp

array([[6.23042070e-307, 1.86918699e-306, 1.69121096e-306,
        1.29061074e-306, 7.56587585e-307, 1.37961302e-306],
       [1.05699242e-307, 8.01097889e-307, 1.78020169e-306,
        7.56601165e-307, 1.02359984e-306, 1.33510679e-306],
       [2.22522597e-306, 1.37961302e-306, 6.89804132e-307,
        1.78020576e-306, 1.60220800e-306, 1.86919106e-306],
       [1.06811422e-306, 1.05700515e-307, 2.04712906e-306,
        7.56589622e-307, 1.11258277e-307, 8.90111708e-307]])

In [ ]:
emp_like=np.empty_like(lspace)
emp_like


array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [12]:
ide=np.identity(45)
ide
ide.shape

(45, 45)

In [ ]:
arr=np.arange(99)
arr
arr.reshape(3,33)
arr
arr=arr.reshape(3,33)
arr
arr=arr.ravel()
arr
arr.shape

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])